import React, { useEffect, useMemo, useState } from 'react';
import { View, StyleSheet, ScrollView, TouchableOpacity } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { Ionicons } from '@expo/vector-icons';
import Typography from '../../components/common/Typography';
import Card from '../../components/common/Card';
import PrimaryButton from '../../components/common/PrimaryButton';
import Dropdown from '../../components/common/Dropdown';
import BackButton from '../../components/common/BackButton';
import { colors } from '../../styles/colors';
import { spacing, borderRadius } from '../../styles/spacing';

/**
 * TrainingSetupScreen — Training configuration before starting a session.
 *
 * Layout (top -> bottom):
 * 1. Back button
 * 2. "Training Setup" header
 * 3. Script type selector (Pre-written / Auto-Generated tabs)
 * 4. Script dropdown selector
 * 5. Focus mode radio buttons (Scripted Accuracy / Free Speech)
 * 6. Start Training button + Cancel
 *
 * State Variables (for web version reuse):
 * - selectedScriptType: 'prewritten' | 'autogenerated'
 * - allScripts: array of available scripts
 * - selectedScriptId: currently selected script ID
 * - selectedFocus: 'accuracy' | 'free'
 * - isLoading: boolean loading state for Supabase fetch
 */
const TrainingSetupScreen = ({ navigation }) => {
  const [selectedScriptType, setSelectedScriptType] = useState('prewritten');
  const [allScripts, setAllScripts] = useState([]);
  const [selectedScriptId, setSelectedScriptId] = useState('');
  const [selectedFocus, setSelectedFocus] = useState(null);
  const [isLoading, setIsLoading] = useState(false);
  const [isStarting, setIsStarting] = useState(false);
  const isFreeFocus = selectedFocus === 'free';

  useEffect(() => {
    const loadScripts = async () => {
      setIsLoading(true);
      // TODO: Replace with Supabase query (practice_scripts) filtered by selectedScriptType.
      const mockScripts = [
        { id: '1', title: 'Graduation Draft 1', type: 'prewritten' },
        { id: '2', title: 'Graduation Draft 2', type: 'prewritten' },
        { id: '3', title: 'Eulogy Draft', type: 'prewritten' },
        { id: '4', title: 'Generated Speech A', type: 'autogenerated' },
      ];
      setAllScripts(mockScripts);
      setSelectedScriptId('');
      setIsLoading(false);
    };

    loadScripts();
  }, [selectedScriptType]);

  /** @type {Array<{label: string, value: string}>} */
  const scriptDropdownOptions = useMemo(
    () =>
      allScripts
        .filter((s) => s.type === selectedScriptType)
        .map((s) => ({ label: s.title, value: s.id })),
    [allScripts, selectedScriptType]
  );

  /** @type {Array<{value: string, label: string}>} */
  const focusOptions = useMemo(
    () => [
      { value: 'accuracy', label: 'Scripted Accuracy' },
      { value: 'free', label: 'Free Speech' },
    ],
    []
  );

  useEffect(() => {
    if (selectedFocus !== 'accuracy') return;
    if (selectedScriptType !== 'prewritten') {
      setSelectedScriptType('prewritten');
      setSelectedScriptId('');
      return;
    }
    if (selectedScriptId) return;
    if (scriptDropdownOptions.length === 0) return;
    setSelectedScriptId(scriptDropdownOptions[0].value);
  }, [selectedFocus, selectedScriptType, selectedScriptId, scriptDropdownOptions]);

  const handleGoBack = () => {
    if (navigation.canGoBack()) {
      navigation.goBack();
    } else {
      navigation.navigate('MainTabs', { screen: 'Dashboard' });
    }
  };

  const handleCancel = () => {
    if (navigation.canGoBack()) {
      navigation.goBack();
    } else {
      navigation.navigate('MainTabs', { screen: 'Dashboard' });
    }
  };

  const handleStartTraining = async () => {
    if (!selectedFocus) {
      console.warn('No focus selected');
      return;
    }
    if (selectedFocus === 'accuracy' && !selectedScriptId) {
      console.warn('No script selected');
      return;
    }
    setIsStarting(true);
    try {
      const params = {
        focusMode: selectedFocus,
        autoStart: true,
        entryPoint: 'training',
      };
      if (selectedFocus === 'accuracy') {
        params.scriptId = selectedScriptId;
        params.scriptType = selectedScriptType;
      }
      // Navigate to TrainingScripted screen with focus mode
      console.info('Start training', params);
      navigation.navigate('TrainingScripted', params);
    } finally {
      setIsStarting(false);
    }
  };

  const handleOpenGenerate = () => {
    navigation.navigate('GenerateScript');
  };

  return (
    <SafeAreaView style={styles.container} edges={['top']}>
      <View style={styles.content}>
        <ScrollView contentContainerStyle={styles.scrollContent}>
          {/* Back button */}
          <BackButton onPress={handleGoBack} style={{ marginBottom: spacing.md }} />

          {/* Header */}
          <Typography variant="h1" align="center" style={styles.title}>
            Training{"\n"}Setup
          </Typography>

          {/* Script Type Tabs */}
          <View style={styles.tabsRow}>
            <TouchableOpacity
              style={[
                styles.tab,
                selectedScriptType === 'prewritten' && styles.tabActive,
              ]}
              onPress={() => setSelectedScriptType('prewritten')}
              activeOpacity={0.7}
            >
              <Typography
                variant="bodySmall"
                weight="medium"
                color={selectedScriptType === 'prewritten' ? 'black' : 'textSecondary'}
              >
                Pre-written
              </Typography>
            </TouchableOpacity>
            <TouchableOpacity
              style={[
                styles.tab,
                selectedScriptType === 'autogenerated' && styles.tabActive,
              ]}
              onPress={() => setSelectedScriptType('autogenerated')}
              activeOpacity={0.7}
            >
              <Typography
                variant="bodySmall"
                weight="medium"
                color={selectedScriptType === 'autogenerated' ? 'black' : 'textSecondary'}
              >
                Auto-Generated
              </Typography>
            </TouchableOpacity>
          </View>

          {/* Script Selector or Generate Button */}
          {selectedScriptType === 'autogenerated' ? (
            <>
              <Typography variant="caption" color="textSecondary" weight="medium" style={styles.selectorLabel}>
                Create a new script
              </Typography>
              <PrimaryButton
                title="Generate Speech"
                onPress={handleOpenGenerate}
                variant="primary"
                size="medium"
                style={styles.generateButton}
              />
            </>
          ) : (
            <>
              <Typography
                variant="caption"
                color="textSecondary"
                weight="medium"
                style={[styles.selectorLabel, isFreeFocus && styles.selectorLabelDisabled]}
              >
                Selected from your library
              </Typography>
              <View
                style={[styles.dropdownWrap, isFreeFocus && styles.dropdownDisabled]}
                pointerEvents={isFreeFocus ? 'none' : 'auto'}
              >
                <Dropdown
                  value={selectedScriptId}
                  options={scriptDropdownOptions}
                  onSelect={setSelectedScriptId}
                  placeholder="Choose a script..."
                />
              </View>
            </>
          )}

          {/* Focus Section */}
          <Typography variant="body" weight="bold" style={styles.focusTitle}>
            CHOOSE YOUR FOCUS
          </Typography>

          {/* Focus Options */}
          {focusOptions.map((option) => (
            <TouchableOpacity
              key={option.value}
              style={[
                styles.focusOption,
                selectedFocus === option.value && styles.focusOptionActive,
              ]}
              onPress={() => setSelectedFocus(option.value)}
              activeOpacity={0.9}
            >
              <View style={styles.radioWrap}>
                <View
                  style={[
                    styles.radioOuter,
                    selectedFocus === option.value && styles.radioActive,
                  ]}
                >
                  {selectedFocus === option.value && (
                    <View style={styles.radioInner} />
                  )}
                </View>
              </View>

              <View style={styles.focusContent}>
                <Typography variant="body" weight="bold" style={styles.focusLabel}>
                  {option.label}
                </Typography>
                <Typography
                  variant="bodySmall"
                  color="textSecondary"
                  numberOfLines={2}
                  style={styles.focusDesc}
                >
                  {option.value === 'accuracy'
                    ? 'Strict adherence to text for pronunciations. AI will track every word.'
                    : 'Impromptu speaking style. Focus on flow, tone, and pacing.'}
                </Typography>
              </View>
            </TouchableOpacity>
          ))}
        </ScrollView>

        {/* Footer */}
        <View style={styles.footer}>
          <PrimaryButton
            title="Start Training"
            onPress={handleStartTraining}
            loading={isStarting}
            disabled={!selectedFocus || (selectedFocus === 'accuracy' && !selectedScriptId)}
            variant="primary"
            size="large"
            style={styles.startButton}
          />
          <PrimaryButton
            title="Cancel"
            onPress={handleCancel}
            variant="outline"
            size="medium"
            style={styles.cancelButton}
          />
        </View>
      </View>
    </SafeAreaView>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  content: {
    flex: 1,
  },
  scrollContent: {
    paddingHorizontal: spacing.md,
    paddingTop: spacing.sm,
    paddingBottom: spacing.xl,
  },

  title: {
    marginBottom: spacing.md,
  },
  tabsRow: {
    flexDirection: 'row',
    gap: spacing.xs,
    marginBottom: spacing.md,
  },
  tab: {
    flex: 1,
    paddingVertical: spacing.xs,
    paddingHorizontal: spacing.sm,
    borderRadius: borderRadius.full,
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: colors.gray300,
    alignItems: 'center',
    justifyContent: 'center',
  },
  tabActive: {
    backgroundColor: colors.primary,
    borderColor: colors.primary,
  },
  selectorLabel: {
    marginTop: spacing.sm,
    marginBottom: spacing.xs,
  },
  selectorLabelDisabled: {
    opacity: 0.5,
  },
  dropdownWrap: {
    width: '100%',
  },
  dropdownDisabled: {
    opacity: 0.5,
  },
  focusTitle: {
    marginTop: spacing.lg,
    marginBottom: spacing.md,
    letterSpacing: 0.5,
  },
  focusOption: {
    flexDirection: 'row',
    paddingVertical: spacing.md,
    paddingHorizontal: spacing.md,
    marginBottom: spacing.sm,
    borderRadius: borderRadius.lg,
    backgroundColor: colors.white,
    borderWidth: 2,
    borderColor: 'transparent',
    alignItems: 'flex-start',
  },
  focusOptionActive: {
    backgroundColor: 'rgba(251, 175, 0, 0.08)',
    borderColor: colors.primary,
  },
  radioWrap: {
    marginRight: spacing.md,
    marginTop: spacing.xs,
  },
  radioOuter: {
    width: 20,
    height: 20,
    borderRadius: 10,
    borderWidth: 2,
    borderColor: colors.textSecondary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  radioActive: {
    borderColor: colors.primary,
  },
  radioInner: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: colors.primary,
  },
  focusContent: {
    flex: 1,
  },
  focusLabel: {
    marginBottom: spacing.xs,
  },
  focusDesc: {
    lineHeight: 18,
  },
  footer: {
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.md,
    gap: spacing.sm,
  },
  startButton: {
    backgroundColor: colors.primary,
  },
  cancelButton: {
    marginBottom: 0,
  },
  generateButton: {
    marginBottom: spacing.md,
  },
});

export default TrainingSetupScreen;
